# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'Test' do
pod 'SDWebImage', '~>3.7'
pod 'SQLite.swift', '~> 0.10.1'
end

